server:
  port: 8001

spring:
  application:
    name: halo-user-feign-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率值介于0到1之间, 1则表示全部采集
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，本次为json，本文要设置为“text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: evildoerA      # 添加分组后自动持久化(让多个消费者处于相同分组竞争关系, 可以解决重复消费问题)
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: halo-user-feign-consumer
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

##这里只把feign做客户端用，不注册进eureka
#eureka:
#  client:
#    #表示是否将自己注册进EurekaServer默认为true
#    register-with-eureka: false
#    service-url:
#      #defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控那个接口
    com.ayxworxfr.springcloud.service.PaymentFeignService: debug

#消费者将去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-service: http://halo-user-provider
