server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8849 #配置Nacos地址
    config:
      server:
        git:
          #uri: git@github.com:ayxworxfr/spring-cloud-config.git #Github上的git仓库名字
          uri: https://github.com/ayxworxfr/spring-cloud-config.git
          ##搜索目录.这个目录指的是github上的目录
          search-paths:
            - spring-cloud-config
      ##读取分支
      label: main
#rabbit相关配置 15672是web管理界面的端口，5672是MQ访问的端口
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://localhost:7001/eureka/

#encrypt:            #加密配置文件
#  key: foobar       #加密因子

#rabbitmq相关设置 ，暴露 bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
