server:
  port: 9527

# 网关配置
spring:
  application:
    name: halo-gateway
#  profiles: local
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849 #配置Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true   # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: user-feign-consumer # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001
          #匹配后提供服务的路由地址
          uri: lb://halo-user-feign-consumer
          # 断言
          predicates:
            -
            # 路径相匹配的进行路由
            - Path=/user/**
#            - After=2021-01-28T15:34:30.361+08:00[Asia/Shanghai]
          filter:
            - SwaggerHeaderFilter3
            - StripPrefix = 1
        - id: halo-user-provider
          uri: lb://halo-user-provider
          predicates:
            - Path=/auth/**
#            - Cookie=username,evildoer   #带Cookie，并且username的值为evildoer
#            - Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
          filter:
            - SwaggerHeaderFilter
            - StripPrefix = 1


#eureka:
#  instance:
#    hostname: exam-gateway
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka/